name: App Build and Deploy workflow

on:
  push:
    branches:
      - live
    paths:
      - 'fastapi/**'

  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_URL }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_URL }}/fastapi-greet:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_URL }}/fastapi-greet:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: fastapi-greet
            image: ${{ secrets.REGISTRY_URL }}/fastapi-greet:${{ github.sha }}
            cpu: 1
            memory: 0.1
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: fastapi-greet-container
            location: ${{ secrets.AZURE_REGION }}
